sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3
  - 2.2
  - 2.1
  - ruby-head
cache: bundler
before_install:
  - gem install bundler -v 1.15.0
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.1
